### ISSUE TITLE
Similar to #17 but only 2 files

### ISSUE THREAD

**Issue by Rich-YoYo** [rickhowe/diffchar.vim#20] opened 2019-03-06 13:53 UTC
Similar to issue #17 but only 2 files involved

How to reproduce;-

I have created two files (hopefully attached) which are basically sanitized versions of real source files I have been working on that provoke this problem. They are quite large, I'm afraid, but I have not been able to reproduce the problem with smaller files.

Using these files, the problem is 100% reproducable using NVIM, but not reproducable using VIM

- gunzip a.gz and b.gz (obvious, but ha-ho)
- > nvim -d ./a ./b
- from the 'b' window, visually select lines 413 to 414 inclusive
- :'<,'>diffget

The folloiwng error appears;-

Error detected while processing function <SNR>41_AdjustDiffCharLines[17]..<SNR>41_SetDiffModeLines:
line  106:
E684: list index out of range: 0

Hitting 'return' will usually elicit lots of other, similar, errors

I'm not sure if I have seen this issue on vim, rather than nvim, in the past.

[a.gz](https://github.com/rickhowe/diffchar.vim/files/2936507/a.gz)
[b.gz](https://github.com/rickhowe/diffchar.vim/files/2936508/b.gz)

**Comment by rickhowe** [comment] 2019-03-07 07:40
I can reproduce the problem in vim and found the reason.
I will fix it and update soon. Thank you.

**Comment by rickhowe** [comment] 2019-03-28 09:27
It is fixed in 8.5.

**Closed by rickhowe** 2019-03-28 09:27 UTC
